### ISSUE TITLE
Accept more PRs

### ISSUE THREAD

**Issue by felixf4xu** [trunk-dev/trunk#19]
Hi,

I know this is a fork, but since the upsteam does not accept PRs actively, it should be better to accept more PRs merged into this repo.

for example, I want https://github.com/thedodd/trunk/pull/616/files be merged. 

If you think it's ok, I can cherry pick that commit and create a PR here.

**Comment by ctron** [comment]
Right now everything is again is a state of flux (or lingering, waiting …). There's the `trunk-rs` repo which thedodd opened, and I have access to it. Then again, the trunk repo is not there an I can't backport the changes from trunk-ng to trunk either.

I don't want to rush anything now, but if you have an opinion, I would ask to raise your voice (in a friendly manner). Discord or Github, whatever works for you.

**Comment by ctron** [comment]
It's merged, released in trunk 0.18.0. I would say we continue work on trunk (proper).
