### ISSUE TITLE
🎉 Back to trunk! 🎉

### ISSUE THREAD

**Issue by ctron** [trunk-dev/trunk#21]
Trunk now has it's own organization: https://github/trunk-rs and `trunk-ng` is merged back into `trunk`.

I think that's the best outcome we could have. And it makes this organization obsolete.

So, I will move this organization's `trunk` repository back to my personal space in the near future. All future development should happen in `trunk-rs`.

**Comment by ctron** [comment]
Trunk 0.18.0 has been released. It contains the changes of trun-ng and it the way forward.

**Comment by ilyvion** [comment]
You might want to put this somewhere more visible than a closed issue, like in the project description or readme file? Took me more than a good minute to figure out that trunk-ng was deprecated by finally finding this.

**Comment by ctron** [comment]
Fixed the link, thanks!

Kind of tricky. It's the only pinned issue. I was hoping that's good enough. Putting that in the readme doesn't work, as that's the readme of the trunk (proper) repository. I updated the link of the "homepage", pointing to https://github.com/trunk-rs/trunk/

**Comment by ilyvion** [comment]
> Putting that in the readme doesn't work, as that's the readme of the trunk (proper) repository.

But this is a fork? Changes made here don't happen there... right? 🤔

**Comment by ctron** [comment]
Yes, it's a fork. But a "traditional" upstream fork. So `main` should be the same as upstream (trunk-rs) main.
